### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'filter')

### ISSUE THREAD

**Issue by williambelle** [epfl-si/search-api#169]
/api/unit?hl=en&showall=0&siteSearch=unit.epfl.ch&acro=UPDANGELO

```
[error]  TypeError: Cannot read properties of null (reading 'filter')
    at Object.getPersonsByUnit (/usr/src/app/services/apimd.service.js:75:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getUnit (/usr/src/app/services/unit.service.js:137:25)
    at async Object.get (/usr/src/app/services/unit.service.js:22:12)
    at async get (/usr/src/app/controllers/unit.controller.js:11:23)
```

**Comment by obieler** [comment]
Normally we receive an empty array instead of a null value ([INC0600895](https://go.epfl.ch/INC0600895)). 
Reported via [INC0628120](https://go.epfl.ch/INC0628120).

**Comment by williambelle** [comment]
Fixed.
